### PR TITLE
Gave multi OS support to your application

### PR DESCRIPTION
**Pull request by nsankethreddy**
Earlier used to support only Windows
Currently Supports Linux, Windows and Mac OS.

Dosent Breaking any existing features.

### CODE REVIEW

**Comment by GauravSingh9356** [comment]
gud job mate

**Comment by nsankethreddy** [comment]
Hey Bruv,
Try making your repo a Hacotober fest acceptable one.
You might get more contributions from other developers and also Ill get an
extra PR for my Count :P

**Comment by GauravSingh9356** [comment]
@nsankethreddy Absolutely bro..Already done.. Check this -> https://github.com/noobDevelopers/J.A.R.V.I.S

**Comment by GauravSingh9356** [comment]
And circulate if possible.Thanks

**Comment by nsankethreddy** [comment]
Boyy fix your repo

**Pull request merged**
